name: T.W. Chang's Blog
description: >
    Something about network or programming.
about: 
master_repo: true
url: "https://blog.wilicw.dev"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo: logo.png

rtl: false
owner:
  name: William Chang
  avatar: "https://avatars.githubusercontent.com/u/18641285"
  email: "me@wilicw.dev"
  twitter: wilicw
  github: https://github.com/wilicw
